#ifndef LEAPS_COMPRESSOR_ERROR_NOERROR

#define LEAPS_COMPRESSOR_ERROR_NOERROR				0
#define LEAPS_COMPRESSOR_ERROR_UNKNOWN				-1
#define LEAPS_COMPRESSOR_ERROR_USER_STOP_ON_READER	1
#define LEAPS_COMPRESSOR_ERROR_USER_STOP_ON_WRITER	2

#endif